apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-git
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/mirik12/flux-gitops
  ref:
    branch: main

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flux
  namespace: flux-system
spec:
  releaseName: flux
  chart:
    spec:
      chart: flux
      version: 1.9.0
      sourceRef:
        kind: GitRepository
        name: flux-git
        namespace: flux-system
  interval: 1m
  values:
    manifestGeneration:
      auto: true
